//
//  Constants.h
//  Mercantilism
//
//  Created by JP Moral on 3/29/12.
//  Copyright (c) 2012 Codeflux. All rights reserved.
//

#ifndef Mercantilism_Constants_h
#define Mercantilism_Constants_h

#define PLAYER_STARTING_MONEY 5000.0f
#define PLAYER_STARTING_DEBT 2000.0f

#define CHANCE_OF_BEING_ROBBED 0.10
#define PERCENT_OF_CASH_ROBBED 0.50

#define DEBT_INTEREST_RATE 0.10
#define INVESTMENT_INTEREST_RATE 0.05

#define NUMBER_OF_LOCATIONS 5

#define RED_TOWN "Red Town"
#define AZURE_VALLEY "Azure Valley"
#define EMERALD_CITY "Emerald City"
#define GREY_CANYON "Grey Canyon"
#define PIRATE_COVE "Pirate Cove"

#define RED_TOWN_MENU "[R]ed Town"
#define AZURE_VALLEY_MENU "[A]zure Valley"
#define EMERALD_CITY_MENU "[E]merald City"
#define GREY_CANYON_MENU "[G]rey Canyon"
#define PIRATE_COVE_MENU "[P]irate Cove"

#define RED_TOWN_LUMBER_MIN_PRICE 10
#define RED_TOWN_LUMBER_MAX_PRICE 40
#define RED_TOWN_STONE_MIN_PRICE 150
#define RED_TOWN_STONE_MAX_PRICE 260
#define RED_TOWN_SILK_MIN_PRICE 400
#define RED_TOWN_SILK_MAX_PRICE 900
#define RED_TOWN_ORE_MIN_PRICE 2200
#define RED_TOWN_ORE_MAX_PRICE 3800
#define RED_TOWN_GEM_MIN_PRICE 5000
#define RED_TOWN_GEM_MAX_PRICE 9000

#define AZURE_VALLEY_LUMBER_MIN_PRICE 20
#define AZURE_VALLEY_LUMBER_MAX_PRICE 80
#define AZURE_VALLEY_STONE_MIN_PRICE 75
#define AZURE_VALLEY_STONE_MAX_PRICE 130
#define AZURE_VALLEY_SILK_MIN_PRICE 400
#define AZURE_VALLEY_SILK_MAX_PRICE 900
#define AZURE_VALLEY_ORE_MIN_PRICE 2200
#define AZURE_VALLEY_ORE_MAX_PRICE 3800
#define AZURE_VALLEY_GEM_MIN_PRICE 5000
#define AZURE_VALLEY_GEM_MAX_PRICE 9000

#define EMERALD_CITY_LUMBER_MIN_PRICE 20
#define EMERALD_CITY_LUMBER_MAX_PRICE 80
#define EMERALD_CITY_STONE_MIN_PRICE 150
#define EMERALD_CITY_STONE_MAX_PRICE 260
#define EMERALD_CITY_SILK_MIN_PRICE 200
#define EMERALD_CITY_SILK_MAX_PRICE 450
#define EMERALD_CITY_ORE_MIN_PRICE 2200
#define EMERALD_CITY_ORE_MAX_PRICE 3800
#define EMERALD_CITY_GEM_MIN_PRICE 5000
#define EMERALD_CITY_GEM_MAX_PRICE 9000

#define GREY_CANYON_LUMBER_MIN_PRICE 20
#define GREY_CANYON_LUMBER_MAX_PRICE 80
#define GREY_CANYON_STONE_MIN_PRICE 150
#define GREY_CANYON_STONE_MAX_PRICE 260
#define GREY_CANYON_SILK_MIN_PRICE 400
#define GREY_CANYON_SILK_MAX_PRICE 900
#define GREY_CANYON_ORE_MIN_PRICE 1100
#define GREY_CANYON_ORE_MAX_PRICE 1900
#define GREY_CANYON_GEM_MIN_PRICE 5000
#define GREY_CANYON_GEM_MAX_PRICE 9000

#define PIRATE_COVE_LUMBER_MIN_PRICE 20
#define PIRATE_COVE_LUMBER_MAX_PRICE 80
#define PIRATE_COVE_STONE_MIN_PRICE 150
#define PIRATE_COVE_STONE_MAX_PRICE 260
#define PIRATE_COVE_SILK_MIN_PRICE 400
#define PIRATE_COVE_SILK_MAX_PRICE 900
#define PIRATE_COVE_ORE_MIN_PRICE 2200
#define PIRATE_COVE_ORE_MAX_PRICE 3800
#define PIRATE_COVE_GEM_MIN_PRICE 2500
#define PIRATE_COVE_GEM_MAX_PRICE 4500

#define RED_TOWN_LUMBER_MIN_RESTOCK 40
#define RED_TOWN_LUMBER_MAX_RESTOCK 100
#define RED_TOWN_STONE_MIN_RESTOCK 45
#define RED_TOWN_STONE_MAX_RESTOCK 105
#define RED_TOWN_SILK_MIN_RESTOCK 20
#define RED_TOWN_SILK_MAX_RESTOCK 45
#define RED_TOWN_ORE_MIN_RESTOCK 10
#define RED_TOWN_ORE_MAX_RESTOCK 20
#define RED_TOWN_GEM_MIN_RESTOCK 5
#define RED_TOWN_GEM_MAX_RESTOCK 10

#define AZURE_VALLEY_LUMBER_MIN_RESTOCK 40
#define AZURE_VALLEY_LUMBER_MAX_RESTOCK 100
#define AZURE_VALLEY_STONE_MIN_RESTOCK 30
#define AZURE_VALLEY_STONE_MAX_RESTOCK 70
#define AZURE_VALLEY_SILK_MIN_RESTOCK 30
#define AZURE_VALLEY_SILK_MAX_RESTOCK 65
#define AZURE_VALLEY_ORE_MIN_RESTOCK 10
#define AZURE_VALLEY_ORE_MAX_RESTOCK 20
#define AZURE_VALLEY_GEM_MIN_RESTOCK 5
#define AZURE_VALLEY_GEM_MAX_RESTOCK 10

#define EMERALD_CITY_LUMBER_MIN_RESTOCK 60
#define EMERALD_CITY_LUMBER_MAX_RESTOCK 150
#define EMERALD_CITY_STONE_MIN_RESTOCK 30
#define EMERALD_CITY_STONE_MAX_RESTOCK 70
#define EMERALD_CITY_SILK_MIN_RESTOCK 20
#define EMERALD_CITY_SILK_MAX_RESTOCK 45
#define EMERALD_CITY_ORE_MIN_RESTOCK 10
#define EMERALD_CITY_ORE_MAX_RESTOCK 20
#define EMERALD_CITY_GEM_MIN_RESTOCK 5
#define EMERALD_CITY_GEM_MAX_RESTOCK 10

#define GREY_CANYON_LUMBER_MIN_RESTOCK 40
#define GREY_CANYON_LUMBER_MAX_RESTOCK 100
#define GREY_CANYON_STONE_MIN_RESTOCK 30
#define GREY_CANYON_STONE_MAX_RESTOCK 70
#define GREY_CANYON_SILK_MIN_RESTOCK 20
#define GREY_CANYON_SILK_MAX_RESTOCK 45
#define GREY_CANYON_ORE_MIN_RESTOCK 10
#define GREY_CANYON_ORE_MAX_RESTOCK 20
#define GREY_CANYON_GEM_MIN_RESTOCK 8
#define GREY_CANYON_GEM_MAX_RESTOCK 15

#define PIRATE_COVE_LUMBER_MIN_RESTOCK 40
#define PIRATE_COVE_LUMBER_MAX_RESTOCK 100
#define PIRATE_COVE_STONE_MIN_RESTOCK 30
#define PIRATE_COVE_STONE_MAX_RESTOCK 70
#define PIRATE_COVE_SILK_MIN_RESTOCK 20
#define PIRATE_COVE_SILK_MAX_RESTOCK 45
#define PIRATE_COVE_ORE_MIN_RESTOCK 15
#define PIRATE_COVE_ORE_MAX_RESTOCK 30
#define PIRATE_COVE_GEM_MIN_RESTOCK 5
#define PIRATE_COVE_GEM_MAX_RESTOCK 10

#define VALID_MAIN_MENU_CHOICES "PHQ"
#define VALID_LOCATION_CHOICES "BRAEGPQ"
#define VALID_BANK_ACTIONS "LPM"

#endif
